<?php

$router->get('/', 'HomeController@index');
$router->get('/article', 'HomeController@article');
$router->get('/login', 'AuthController@login', ["IsGuest"]);
$router->get('/author/authorDash', 'AuthorController@authorDash', ["IsAuthed", "IsAuthor"]);
$router->get('/admin/category', 'AdminController@category', ["IsAuthed", "IsAdmin"]);
$router->get('/admin/members', 'AdminController@members', ["IsAuthed", "IsAdmin"]);
$router->get('/register', 'AuthController@register', ["IsGuest"]);
$router->post('/login', 'AuthController@submitLogin', ["IsGuest"]);
$router->post('/register', 'AuthController@submitRegister', ["IsGuest"]);
$router->post('/logout', 'AuthController@logout', ["IsAuthed"]);
$router->get('/admin', 'AdminController@dashboard', ["IsAuthed", "IsAdmin"]);
$router->get('/admin/category/create', 'CategoryController@create', ["IsAuthed", "IsAdmin"]);
$router->get('/admin/category/edit', 'CategoryController@edit', ["IsAuthed", "IsAdmin"]);
$router->post('/admin/category/store', 'CategoryController@store', ["IsAuthed", "IsAdmin"]);
$router->post('/admin/category/update', 'CategoryController@update', ["IsAuthed", "IsAdmin"]);
$router->post('/admin/category/delete', 'CategoryController@delete', ["IsAuthed", "IsAdmin"]);
$router->get('/author/article/create', 'ArticleController@create', ["IsAuthed", "IsAuthor"]);
$router->get('/author/article/edit', 'ArticleController@edit', ["IsAuthed", "IsAuthor"]);
$router->get('/author/articles', 'AuthorController@manageArticles', ["IsAuthed", "IsAuthor"]);
$router->post('/author/article/store', 'ArticleController@store', ["IsAuthed", "IsAuthor"]);
$router->post('/author/article/update', 'ArticleController@update', ["IsAuthed", "IsAuthor"]);
$router->get('/author/article/delete', 'ArticleController@delete', ["IsAuthed", "IsAuthor"]);
$router->post('/like', 'LikeController@likeArticle', ["IsAuthed", "IsReader"]);
$router->post('/unlike', 'LikeController@unlikeArticle', ["IsAuthed", "IsReader"]);
$router->post('/comments/store', 'CommentController@addComment', ["IsAuthed", "IsReader"]);
$router->post('/comments/delete', 'CommentController@deleteComment', ["IsAuthed", "IsReader"]);
$router->post('/comments/update', 'CommentController@updateComment', ["IsAuthed", "IsReader"]);
$router->get('/author/likes', 'AuthorController@likes', ["IsAuthed", "IsAuthor"]);